# Generated by Django 4.1.7 on 2023-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resguardos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('gid', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'resguardos',
            },
        ),
    ]
