# Generated by Django 4.1.7 on 2023-02-26 16:36

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resguardo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField()),
            ],
        ),
        migrations.AddField(
            model_name='resguardos',
            name='signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resguardo.signaturemodel'),
            preserve_default=False,
        ),
    ]
